[google_service_account]
type = "service_account"
project_id = "vet-post-op-drug-records"
private_key_id = "6febf97f5c81edcf2f2fa790f40ea5525aa21e3c"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZUBIrn9XHZk3u\\nOgyK2YBiGTFNGRD+RgGVLseB+N7K9fIJe/+uS1rJP9fKe4SLl5zITaF4EvHPCEBH\\n...\\n-----END PRIVATE KEY-----\\n"
client_email = "service-account@vet-post-op-drug-records.iam.gserviceaccount.com"
client_id = "105438993573822531172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40vet-post-op-drug-records.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

